language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2

env:
  global:
    - TERM=dumb

install: true

script:
#  - ci/run_test_h2.sh -p digdag-core --tests '*AESGCMSecretCryptoTest*'
  - ./gradlew clean cleanTest test --info --no-daemon -p digdag-core --tests '*AESGCMSecretCryptoTest*'
