sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

cache:
  directories:
    - $HOME/docker
    - $HOME/.gradle
    - $HOME/.m2

env:
  global:
    - TERM=dumb

before_install:
  - sudo docker/setup.sh

install: true

script:
#  - ci/run_test_h2.sh -p digdag-core --tests '*AESGCMSecretCryptoTest*'
  - ./gradlew clean cleanTest test --info --no-daemon -p digdag-core --tests '*AESGCMSecretCryptoTest*'
